from textwrap import dedent

from src.advent_of_code_2025.day7 import get_split_count


def test_get_split_count() -> None:
    input_string = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    input_string = dedent(input_string)

    input_lines = [list(row) for row in input_string.strip().split("\n")]

    output = get_split_count(input_lines)

    expected = 22

    assert output == expected
